(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap11111111111111111 = function() {
	this.initialize(img.Bitmap11111111111111111);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,198,112);


(lib.hpa_slots_bg = function() {
	this.initialize(img.hpa_slots_bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,800);


(lib.hpa_slots_quali_asset1 = function() {
	this.initialize(img.hpa_slots_quali_asset1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,206);


(lib.hpa_slots_quali_device = function() {
	this.initialize(img.hpa_slots_quali_device);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,544);


(lib.hpa_slots_quali_device2 = function() {
	this.initialize(img.hpa_slots_quali_device2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,553);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.mc_sujet = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.hpa_slots_bg();
	this.instance.setTransform(-200,-400);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_sujet, new cjs.Rectangle(-200,-400,400,800), null);


(lib.mc_shl1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAPIgDgBIgBgDIAAgVIABgDIADgBIARAAIACABIACADIAAAVIgCADIgCABg");
	this.shape.setTransform(91.5,29.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAEBEQgFgCgEgDQgDgEgDgGQgBgFAAgLIAAg+IgTgDIgCAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIATAAIAAgQIABgDIADAAIASgEIAAAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAUIASAAQABAAAAABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAAAAAABQABAAAAABIAAAMIgCACIgDABIgSAAIAAA+IAAAHIABACQABABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAEABIALAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBABIgGABIgHAAIgPgBg");
	this.shape_1.setTransform(84.8,24);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVBMQgGgBgFgEQgFgEgDgGQgDgGAAgLIAAAAQAAgSALgIQAMgJAZAAIAMAAIAAgJQAAgIgEgEQgEgDgJAAIgSABIgOABIgBAAIgCgBIgBgDIAAgMQAAgEADgBIAPgCIASgBQAVAAAMAJQALAKAAASIAABIIgBADIgDABIgRAAIgDgBIgBgDIAAgDQgHAEgHACQgGADgHAAQgHAAgGgCgAgFAcQgFABgCACQgDACgBADIAAAIIAAAAQAAAIADACQADADAIAAIAKgCQAFgBAEgDIAAgYIgMAAIgKABgAAPgzIgDgBIgBgDIAAgSIABgDIADgBIAPAAIADABIABADIAAASIgBADIgDABgAgYgzIgDgBIgBgDIAAgSIABgDIADgBIAPAAIACABIACADIAAASIgCADIgCABg");
	this.shape_2.setTransform(75.125,23.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAEBEQgFgCgEgDQgEgEgBgGQgCgFAAgLIAAg+IgTgDIgDAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIATAAIAAgQIABgDIADAAIARgEIABAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAUIASAAQAAAAAAABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIAAAMIgBACIgCABIgSAAIAAA+IAAAHIABACQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAEABIALAAQAEAAAAADIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAABIgHABIgIAAIgOgBg");
	this.shape_3.setTransform(65.75,24);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIBNIgDgCIgBgCIAAhoIABgDIADgBIARAAIADABIABADIAABoIgBACIgDACgAgJgyIgCgBIgCgDIAAgSQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIATAAIADACIABACIAAASIgBADIgDABg");
	this.shape_4.setTransform(59.075,23.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgIBMIgDgBIgBgDIAAiPIABgDIADgBIARAAIADABIABADIAACPIgBADQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(53.675,23.15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA4QgGgBgFgEQgFgEgDgGQgDgGAAgLIAAAAQAAgSALgHQAMgJAZAAIAMAAIAAgJQAAgJgEgEQgEgDgJAAIgSABIgOABIgBAAIgCgBIgBgDIAAgMQAAgEADgBIAPgCIASgBQAVAAAMAJQALAKAAATIAABHIgBADIgDABIgRAAIgDgBIgBgDIAAgDQgHAEgHACQgGADgHAAQgHAAgGgCgAgFAIQgFABgCACQgDACgBADIAAAIIAAAAQAAAIADACQADADAIAAIAKgCQAFgBAEgDIAAgYIgMAAIgKABg");
	this.shape_6.setTransform(45.275,25.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZA3QgGgCgEgEQgGgGgCgJQgCgJAAgNIAAhAIABgDIADgBIASAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIAABAIABAMQABAFADADIAFACIAHABIAFgBIAGgCIAGgCIAFgDIAAhPIABgDIADgBIASAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIAABoIgBADIgDABIgSAAIgDgBIgBgDIAAgFQgIAFgHADQgGACgKAAQgHAAgHgCg");
	this.shape_7.setTransform(34.125,25.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAGBaQgGgBgDgDQgEgEgDgFQgCgGAAgIIAAgEQgKgCgIgEQgIgFgGgHQgGgIgDgKQgDgLAAgNIAAgbQAAgRAEgLQAFgMAHgIQAIgHAKgEQALgDALAAQAMAAALADQAKAEAIAHQAHAIAFAMQAEALAAARIAAAbQAAANgDALQgEAKgFAIQgGAHgIAFQgIAEgKACIAAAEQAAAFACABIAEABIATAAIAEABQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAANQAAADgEAAIgJACIgLAAQgHAAgGgBgAgVg5QgHAIAAAVIAAAbQAAATAHAJQAHAJAOAAQAPAAAHgJQAHgJAAgTIAAgbQAAgVgHgIQgHgJgPAAQgOAAgHAJg");
	this.shape_8.setTransform(21.3,24.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYA5IgDgBIgBgDIAAhoIABgCIADgCIARAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIAAAFQAGgHAIgBIANgCIACABIACADIAAAOQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgCABQgIAAgHACIgMAGIAABPQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_9.setTransform(6.1,25.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AABA6QgHAAgJgDQgIgCgHgFQgHgGgFgKQgFgKAAgOIAAgOQAAgMAEgJQACgKAHgGQAGgHAIgDQAJgEALAAQALAAAJAEQAJAEAHAGQAFAHAEAJQADAKAAALIAAAKQAAAFgEAAIhBAAIAAABIABAJQACAEADAEQACADAFADQAEACAGAAIAVgBIAQgBIABAAIACABQABAAAAAAQAAAAAAABQAAAAAAAAQABABAAAAIAAANIgCAEQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgJACIgJABIgJABIgLAAgAgPgcQgFAGgBAMIAAABIAqAAIAAgBQAAgLgGgHQgFgGgKAAQgIAAgHAGg");
	this.shape_10.setTransform(-3.85,25.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAEBEQgFgCgDgDQgFgEgCgGQgBgFAAgLIAAg+IgTgDIgDAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIATAAIAAgQIABgDIADAAIARgEIABAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAUIASAAQAAAAAAABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIAAAMIgBACIgCABIgSAAIAAA+IAAAHIABACQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAEABIALAAQAEAAAAADIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAABIgIABIgHAAIgOgBg");
	this.shape_11.setTransform(-13.7,24);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgFA6IgKgBIgKgBIgJgCQgEgBAAgEIAAgMIABgCQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIABAAIAIABIALABIAJAAIAGAAIAGAAIAFgDIACgDIAAgDQAAgDgCgCIgHgGIgagQQgHgEgGgHQgEgHAAgJQAAgeAmAAIAKAAIAJABIAIACIAHABQAEABAAAEIAAALQAAAEgDAAIgBAAIgGgBIgIAAIgKgBIgJAAQgGAAgEACQgCABAAAFQAAABAAAAQAAABAAABQAAAAABAAQAAABAAAAIAHAEIAZAQIAKAHIAFAHIADAIIABAIQAAAGgCAGQgDAGgFAEQgFAEgHACQgIADgKAAIgFAAg");
	this.shape_12.setTransform(-22.6,25.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAYBMIgDgBIgBgDIAAhCIgBgKIgCgHQgCgCgDgBIgJgBQgJAAgNAHIAABQQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgSAAIgDgBIgBgDIAAiPIABgDIADgBIASAAIADABQAAAAAAABQABAAAAAAQAAABAAAAQAAAAAAABIAAApQAGgDAHgCQAGgCAKAAQALAAAHAEQAHACAEAHQAEAFABAIQACAJAAAIIAABCQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_13.setTransform(-33.375,23.15);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgJA3QgJgDgGgGQgGgGgDgJQgEgKAAgMIAAgRQAAgNAEgJQADgJAGgGQAGgGAJgDQAIgDAJAAIAQABIAKACIADABIABAEIAAANIgBACIgDABIAAAAIgGgBIgFAAIgHAAIgIAAIgHABQgDABgCADIgFAIQgBAFAAAIIAAARQAAAIABAFIAFAIQACADADABIAHABIAIAAIAHAAIAFAAIAGgBIAAAAIADABIABACIAAANIgBAEIgDABIgKACIgQABQgJAAgIgDg");
	this.shape_14.setTransform(-43.975,25.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUBKQgJgEgFgGQgHgHgDgKQgDgJAAgKIAAgRQAAgKADgIQADgKAHgGQAFgHAJgDQAJgEALAAQAMAAAJAEQAJADAGAHQAGAGADAKQADAIAAAKIAAARQAAAKgDAJQgDAKgGAHQgGAGgJAEQgJAEgMgBQgLABgJgEgAgPgHQgFAHAAALIAAARQAAAMAFAHQAGAIAJAAQALAAAFgIQAGgHAAgMIAAgRQAAgLgGgHQgFgHgLAAQgJAAgGAHgAANgzIgDgBIgCgDIAAgRQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIADgCIAOAAIADACQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAARIgBADIgDABgAgagzIgDgBIgCgDIAAgRQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAIAOAAIADACQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAARIgBADIgDABg");
	this.shape_15.setTransform(-54.425,23.15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAYBMIgDgBIgBgDIAAhCIgBgKIgCgHQgCgCgDgBIgJgBQgJAAgNAHIAABQQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgSAAIgDgBIgBgDIAAiPIABgDIADgBIASAAIADABQAAAAAAABQABAAAAAAQAAABAAAAQAAAAAAABIAAApQAGgDAHgCQAGgCAKAAQALAAAHAEQAHACAEAHQAEAFABAIQACAJAAAIIAABCQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_16.setTransform(-66.025,23.15);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAYA5IgDgBIgBgDIAAhBIgBgLIgCgGQgCgCgDgCQgDgBgGAAQgFAAgFACIgMAGIAABPQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgSAAIgDgBIgBgDIAAhoIABgCIADgCIARAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAFIAIgFIAIgDIAGgBIAKgBQAKAAAHAEQAHACAEAHQADAFACAJQABAIAAAJIAABBQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_17.setTransform(-82.825,25.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgIBNIgDgCIgBgCIAAhoIABgDIADgBIARAAIADABIABADIAABoIgBACIgDACgAgJgyIgCgBIgCgDIAAgSQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIATAAIADACIABACIAAASIgBADIgDABg");
	this.shape_18.setTransform(-91.425,23.075);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgFA6IgKgBIgKgBIgJgCQgEgBAAgEIAAgMIABgCQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAAAAIAJABIAKABIAJAAIAGAAIAGAAIAFgDIACgDIAAgDQAAgDgCgCIgHgGIgagQQgHgEgFgHQgFgHAAgJQAAgeAmAAIAKAAIAJABIAIACIAHABQAEABAAAEIAAALQAAAEgDAAIgBAAIgFgBIgJAAIgKgBIgJAAQgGAAgEACQgCABAAAFQgBABABAAQAAABAAABQAAAAABAAQAAABAAAAIAHAEIAZAQIAKAHIAGAHIACAIIABAIQAAAGgCAGQgDAGgFAEQgFAEgHACQgIADgJAAIgGAAg");
	this.shape_19.setTransform(95.85,0.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAEBEQgFgCgDgDQgEgEgDgGQgBgFAAgLIAAg+IgTgDIgCAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIATAAIAAgQIABgDIADAAIASgEIAAAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAUIATAAQAAAAAAABQABAAAAAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIAAAMIgBACIgCABIgTAAIAAA+IAAAGIABADQABABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAEABIALAAQABAAABAAQABAAAAAAQABABAAAAQAAABAAABIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBABIgHABIgGAAIgPgBg");
	this.shape_20.setTransform(86.85,-0.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUA2QgIgEgHgGQgFgHgEgJQgDgJAAgLIAAgPQAAgLADgJQAEgJAFgHQAHgGAIgEQAJgEALAAQAMAAAIAEQAKAEAFAGQAHAHACAJQAEAJAAALIAAAPQAAALgEAJQgCAJgHAHQgFAGgKAEQgIAEgMAAQgLAAgJgEgAgPgbQgGAHABANIAAAPQgBAMAGAIQAFAHAKAAQAKAAAGgHQAGgIAAgMIAAgPQAAgNgGgHQgGgHgKAAQgKAAgFAHg");
	this.shape_21.setTransform(77.1,0.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgIBMIgDgCIgBgCIAAiPIABgDIADgBIARAAIADABIABADIAACPIgBACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_22.setTransform(68.625,-1.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXBLIgQgDIgCgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgOQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBABAAIACgBIAAAAIAJABIAJAAIAKABIAIAAQAMAAAFgFQAFgEAAgJIgBgFQgBgDgCgCIgEgEIgJgGIgZgOIgMgJQgEgEgDgFQgDgEgBgFIgBgKQAAgIACgHQADgHAGgFQAGgFAJgDQAKgDANAAIALAAIAKABIAKABIAIACIACABIABACIAAAPIgBADIgCABIgUgCIgUAAQgLAAgEAEQgFADAAAHIAAAFIADAEIAFAEIAIAFIAXANQAJAFAEAEQAGAEADAFQADAFACAGIABALQAAAIgDAHQgCAIgHAGQgGAFgJAEQgLAEgNAAIgUgBg");
	this.shape_23.setTransform(60.2,-0.975);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AABA6QgHAAgIgDQgJgCgHgFQgHgGgFgKQgFgKAAgOIAAgOQAAgMAEgJQACgKAHgGQAGgHAIgDQAJgEALAAQALAAAKAEQAJAEAGAGQAFAHAEAJQADAKAAALIAAAKQAAAFgEAAIhBAAIAAABIABAJQACAEADAEQACADAFADQAEACAHAAIAUgBIARgBIAAAAIACABIABACIAAANIgBAEQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgKACIgJABIgIABIgMAAgAgOgcQgHAGAAAMIAAABIAqAAIAAgBQAAgLgGgHQgFgGgKAAQgJAAgFAGg");
	this.shape_24.setTransform(43.75,0.825);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgHA4QgEAAgDgDQgDgCgDgDIgEgJIgZhaIAAgCQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAUAAQADAAABAEIATBTIACAEIABABIACgBIACgEIAThTQABgEADAAIAUAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAACIgZBaQgCAFgCAEIgGAFQgEADgEAAIgHABIgHgBg");
	this.shape_25.setTransform(32.525,0.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgIBNIgDgCIgBgCIAAhoIABgDIADgBIARAAIADABIABADIAABoIgBACIgDACgAgJgyIgCgBIgCgDIAAgSQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIATAAIADACIABACIAAASIgBADIgDABg");
	this.shape_26.setTransform(24.325,-1.225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgFA6IgKgBIgKgBIgJgCQgEgBAAgEIAAgMIABgCQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAAAAIAJABIAKABIAJAAIAGAAIAGAAIAFgDIACgDIAAgDQAAgDgCgCIgHgGIgagQQgIgEgEgHQgFgHAAgJQAAgeAmAAIAKAAIAJABIAIACIAHABQAEABAAAEIAAALQAAAEgDAAIgBAAIgFgBIgJAAIgKgBIgJAAQgGAAgEACQgDABAAAFQAAABABAAQAAABAAABQAAAAABAAQAAABAAAAIAGAEIAaAQIAJAHIAHAHIACAIIABAIQAAAGgCAGQgDAGgFAEQgFAEgHACQgIADgJAAIgGAAg");
	this.shape_27.setTransform(16.75,0.825);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgZA3QgGgCgEgEQgGgGgCgJQgCgJAAgNIAAhAIABgDIADgBIASAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIAABAIABAMQABAFADADIAFACIAHABIAFgBIAGgCIAGgCIAFgDIAAhPIABgDIADgBIASAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAABAAIABADIAABoIgBADIgDABIgSAAIgDgBIgBgDIAAgFQgIAFgHADQgGACgKAAQgHAAgHgCg");
	this.shape_28.setTransform(5.975,0.875);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgIBMIgDgCIgBgCIAAiPIABgDIADgBIARAAIADABIABADIAACPIgBACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_29.setTransform(-2.675,-1.15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AASBMIgDgCIgCgCIgfgtIAAAtQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgSAAIgDgCIgBgCIAAiPIABgDIADgBIASAAIADABQAAAAAAABQABAAAAAAQAAABAAAAQAAAAAAABIAABSIAhgsIADgCIACgBIAWAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAABIgBABIgoAxIApA3IAAACIAAABIgCABg");
	this.shape_30.setTransform(-10.575,-1.15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAaA5IgCgBIgEgEIgVgjIgWAjIgDAEIgCABIgUAAQgBAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgCIAkg1IghgyIgBgCIABgCIADgBIAWAAIADABIACAEIATAfIATgfIADgEIADgBIAUAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAACIghAyIAlA1IAAACIgBACIgCABg");
	this.shape_31.setTransform(-22,0.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AABA6QgHAAgIgDQgJgCgHgFQgHgGgFgKQgFgKAAgOIAAgOQAAgMAEgJQACgKAHgGQAGgHAIgDQAKgEAKAAQALAAAKAEQAIAEAGAGQAHAHACAJQAEAKAAALIAAAKQAAAFgEAAIhBAAIAAABIABAJQABAEAEAEQACADAEADQAFACAHAAIAUgBIARgBIAAAAIACABIABACIAAANIgBAEQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgKACIgIABIgJABIgMAAgAgOgcQgHAGAAAMIAAABIAqAAIAAgBQAAgLgGgHQgFgGgKAAQgJAAgFAGg");
	this.shape_32.setTransform(-33.3,0.825);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAAA6QgGAAgJgDQgIgCgHgFQgHgGgFgKQgFgKAAgOIAAgOQAAgMADgJQADgKAGgGQAHgHAJgDQAJgEAKAAQAMAAAIAEQAKAEAFAGQAHAHACAJQAEAKAAALIAAAKQAAAFgEAAIhAAAIAAABIABAJQAAAEADAEQADADAEADQAFACAGAAIAVgBIARgBIAAAAIADABIAAACIAAANIAAAEQgBAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgKACIgIABIgJABIgNAAgAgPgcQgFAGAAAMIAAABIApAAIAAgBQAAgLgFgHQgHgGgJAAQgIAAgHAGg");
	this.shape_33.setTransform(-49.8,0.825);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgIBMIgDgCIgBgCIAAiPIABgDIADgBIARAAIADABIABADIAACPIgBACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_34.setTransform(-58.275,-1.15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AABA6QgHAAgJgDQgIgCgHgFQgIgGgEgKQgFgKAAgOIAAgOQAAgMAEgJQACgKAHgGQAFgHAKgDQAIgEALAAQALAAAJAEQAJAEAHAGQAGAHADAJQADAKAAALIAAAKQAAAFgEAAIhBAAIAAABIACAJQABAEACAEQADADAFADQAEACAGAAIAVgBIAQgBIABAAIADABIABACIAAANIgBAEQgBAAAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgJACIgJABIgJABIgLAAgAgPgcQgFAGgBAMIAAABIAqAAIAAgBQAAgLgFgHQgHgGgJAAQgIAAgHAGg");
	this.shape_35.setTransform(-66.75,0.825);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgIBNIgDgCIgBgCIAAhoIABgDIADgBIARAAIADABIABADIAABoIgBACIgDACgAgJgyIgCgBIgCgDIAAgSQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIATAAIADACIABACIAAASIgBADIgDABg");
	this.shape_36.setTransform(-75.175,-1.225);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgqBNIgDgBIgBgDIAAiKIABgEIAFgCIAUgEIAUgBQAXAAAMANQAMAOAAAXIAAAQQAAAWgMAOQgMANgXAAIgJAAIgKgCIAAAkIgCADIgCABgAgLg2IgIABIAABFIAKABIAJAAQAFAAAEgCQAFgCACgEQADgEAAgFIABgKIAAgQIgBgLQAAgFgDgEQgCgEgFgCQgEgCgFAAIgLAAg");
	this.shape_37.setTransform(-83.425,2.725);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgYBLIgPgDIgDgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgOQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIADgBIAAAAIAIABIAKAAIALABIAGAAQANAAAFgFQAFgEAAgJIgBgFQgBgDgBgCIgGgEIgIgGIgagOIgLgJQgEgEgDgFQgDgEgBgFIgBgKQAAgIADgHQACgHAGgFQAGgFAJgDQAKgDANAAIAKAAIALABIALABIAGACIADABIABACIAAAPIgBADIgDABIgUgCIgTAAQgKAAgGAEQgEADAAAHIABAFIACAEIAFAEIAIAFIAXANQAIAFAGAEQAFAEAEAFQACAFACAGIABALQAAAIgCAHQgDAIgGAGQgHAFgKAEQgKAEgOAAIgUgBg");
	this.shape_38.setTransform(-95.1,-0.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_shl1, new cjs.Rectangle(-139.1,-15.5,278.2,52.6), null);


(lib.mc_red_footer = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D70A2D").s().p("EhtPBbKMAAAi2TQARKvIUJ2QITJzPIHkQPHHkTnEJQUTETWOAAQWOAAUUkTQTmkJPInkQPInkITpzQIUp1ARqwMAAAC2Tg");
	this.shape.setTransform(-0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_red_footer, new cjs.Rectangle(-699.2,-583.3,1398.4,1166.6999999999998), null);


(lib.mc_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// slots
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmHGBQgfgHgXgQQgXgPgOgeQgNgfAAguIAAlqQAAgFAEgFQAFgFAFAAIBcAAQAFAAAFAFQAEAFAAAFIAAFqQAAAaAKAMQAKAKAZAAIB5AAQAFAAAFAEQAEAFAAAFIAABCQAAALgOADQgpAJhKAAQglAAgegGgAJqFsQgOgEAAgKIAAhFQAAgNANAAIACAAQAPACA3ADQAtADASAAQAkABAOgMQANgLAAgbQAAgQgKgKQgKgLgagQIhhg6QgegRgUgXQgTgVgHgYQgHgYAAgYQAAg/AqglQAqglBgAAQAoAAArAFQAuAFAUAFQAKADAAAKIAABHQAAAMgMAAIiWgIQgdAAgNAJQgNAKAAASQAAAOAJAKQAJAIAdARIBaAwQAkATAUAWQAWAXAIAYQAJAYAAAfQAAAegLAaQgKAagXAYQgXAWglAMQgkANg0ABQhKAAg7gQgAiZDXQg6g3AAh0IAAhTQAAhzA5g3QA5g3BeAAQAtAAAlANQAmAMAcAbQAcAcAPArQAQArAAA7IAABTQAAB0g5A3Qg5A3hdAAQheAAg4g3gAgziSQgTAMgKAbQgJAbAAApIAABTQAAAqAJAaQAKAcASAMQATANAeAAQAsgBAVgcQAVgdAAg/IAAhTQAAg+gVgdQgVgcgsgBQgeAAgSANgAFpCWQgGAAgEgEQgEgEAAgGIAAmYIhzAAQgGAAgEgEQgEgEAAgFIAAhJQAAgFAEgEQAEgFAGAAIFdAAQAFAAAFAFQAEAEAAAFIAABJQAAAFgEAEQgFAEgFAAIhyAAIAAGYQAAAGgEAEQgFAEgFAAgAuQCAQgPgEAAgKIAAhEQAAgOANAAIACAAIBHAGQAsACATAAQAkAAANgLQANgLAAgZQAAgQgJgLQgKgLgbgQIhhg6QgegRgUgXQgSgVgIgYQgHgVAAgcQAAg/AqglQAqglBgAAQAoAAArAFQAuAFAUAFQAKADAAAKIAABHQAAAMgMAAIiWgHQgdgBgNAKQgNAIAAAUQAAAOAJAKQAJAIAeARIBZAwQAjATAWAWQAVAWAJAZQAIAbAAAcQAAAcgKAcQgKAagXAWQgYAXgkAMQgkAOg1AAQhKAAg6gQg");
	this.shape.setTransform(20.3116,10.7969,0.2561,0.2561);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AneCmQgLgDgDgMIgHgcIgPg5Igfh8QgDgMACgFQACgLANgBIAdAAIAKACQAKAEABALIAbCYIAZh5QAEgSAEgHQAFgKAMAAIAYAAQAKAAAEACQAHAEADALQAGAQAVBrIAXiFQACgIADgEQAFgIALAAIAVAAIAJADQAIAFgDANIgWBbIgKApIgNAzIgCAGQgCAFgDADQgEAFgLACIgYAEQgEABgFgCQgKgEgDgNIAAgBIgbhwIgdB/IgDAKQgGAJgKADIgTAEIgLACIgEAAIgGAAgAjbB2QgIgDAAgMIAAioQAAgLACgEQAEgHAMAAIASAAQAGAAAEACQAHAEAAANIAACjQAAAGgBAEQgDAIgKACIgWAEIgDAAIgGgBgAiIBoQgHgDAAgLIgBihQAAgGACgDQADgHALAAIAOAAIAGACQAHADAAAKIAOgKQARgJARABQAWACALAKQAPANAAAbIAABuIgBAKQgCAFgJACIgRADQgKACgDgIQgBgDAAgFIAAhuIgCgIQgDgJgIgBQgHgCgJAEQgKAEgJALIAAByIgBAKQgDAHgJADIgLACIgJACIgDAAIgEgBgAAZBRQgHgDAAgMQgBg8AkgkIAqgkIAIgJQAIgKABgIQABgKgFgIQgFgIgKgDQgHgDgLABIgNAEIgVAIQgHADgGgGQgDgDgEgHIgCgGIgBgIQABgIAJgFQAMgHARgEQAYgFAUAFQAWAGANAOQAOANAEAXQADAVgKAVQgIARgPANIghAdQgGAFgGAHQgNARAAANIBJgIIAIABQAHACAAAIIAAANQAAAFgBADQgDAGgJABIhrAPIgJgBgAHUBFIgBgHIAAgGQACgEAHgBIAVgCIAEgBQAFgCABgGIACgKIABgDQgJADgFAAQgaACgMgNQgFgGgEgKIgNhPIAAgEQABgDACgCQADgCAFAAIANAAQAFAAADADQACACABADIABAFIAKBCIACAGQAEAGAJgBQAJAAAFgCIAEhPQABgGAGgCIAFgBIALAAIAFABQAFACAAAFIgEA8IgDA1IgDAMQgFANgLAHIgKAGIgMACIgVADIgBAAQgKAAAAgIgADIA6QgKgDgIgKQgHgJgDgOIgBgOIAAgoQAAgHACgJQADgSALgKQAMgJAOgDQAIgCAGAAIAKACQALADAIAHIAAgzQAAgMALAAIANAAIAIABQAEADAAAIIAACmQAAAIgEADIgGADIgNABIgGgBQgEgCAAgIIgNALQgLAIgMABIgGAAQgKAAgHgDgADbg2QgFAEgCAIIgBAHIAAAqQAAAIAEAGQAEAFAIABQAJABAKgHIAJgIIAAg7QgHgHgHgDQgDgBgFAAIgCgBQgHAAgFAEgAFRAsQgKgCgHgIQgHgGgCgLIgBgKQgBgFACgFQACgLAJgIQAKgJATgEQAQgDASAAIAAgKQAAgDgDgDQgCgFgIgBQgEgBgFAAQgMABgOADQgDABgDgBQgFgBgBgFIgDgLQgBgDABgDQACgEAHgCQAhgGAOADQAUADAMANQALAMAAASIAABEQAAAFgCACQgBADgFABQgEACgGAAIgGAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAQgDgCgBgGQgMAPgRACIgKABQgHAAgGgCgAF1gNQgNABgGAEQgGAEAAAGQAAAFADAEQAEAEAFAAIAHAAQAGgBAFgDQADgCAEgFIAAgSIgMABgAjdhzQgIgJAAgMQAAgMAIgJQAJgIAMAAQAMAAAJAIQAIAJAAAMQAAAMgIAJQgJAIgMAAQgMAAgJgIg");
	this.shape_1.setTransform(-9.8781,-11.555);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_logo, new cjs.Rectangle(-64.6,-28.2,109.5,49), null);


(lib.mc_icn_sicher_erlaubt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIA3IgCAAIgBgCIAAhWIgZAAIgCgBIgBgCIAAgPIABgCIACgBIBJAAIACABIABACIAAAPIgBACIgCABIgYAAIAABWIgBACIgCAAg");
	this.shape.setTransform(111.9026,32.7255);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggA3IgFgBIgDgEIAAgFIAAhZQAAgFABgDQADgCAEAAIAbgBQANAAALADQAKACAFAHQAHAHgBALIAAADQAAAIgDAFQgDAGgGADIAHAEIAFAHQABAFAAAFIAAACQAAAKgDAGQgFAIgFACQgHAFgIABIgRABgAgPAkIAMAAQAJAAAGgEQAFgCgBgIIAAgBQAAgGgDgEQgEgDgIAAIgQAAgAgPgiIAAAZIAQAAQAPAAAAgMIAAgCQAAgGgFgDQgEgDgLAAg");
	this.shape_1.setTransform(102.9525,32.7505);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQA2QgJgDgEgEQgGgFgEgIQgDgIAAgMIAAhCIABgCIACgBIATAAIADABIAAACIAABCQAAAHACAEQACAGADACQAFACAFAAQAGAAAFgCQAEgDABgEQABgFAAgHIAAhCIABgCIADgBIATAAIACABIABACIAABCQAAAMgDAIQgEAJgFAEQgFAEgJADQgHACgKAAQgKAAgGgCg");
	this.shape_2.setTransform(92.5023,32.8005);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAXA4QAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAgBgBIgFgYIgeAAIgEAYQgBABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgUAAQgBAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgBIAWhbQADgKAGgDQAHgEAIAAIALABQAEACAEADQAEAEACAHIAWBbIAAAAIAAABQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAgAgBggIgJApIAVAAIgJgpQAAAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAg");
	this.shape_3.setTransform(82.5522,32.6755);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJA2QgEAAgHgEQgFgDgDgHQgDgHAAgJIAAhMIABgCIACgBIAUAAIACABIABACIAABMQAAAGACACQACACAEAAIAaAAIACABIABACIAAAOQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAQgIACgRAAQgHAAgGgCg");
	this.shape_4.setTransform(74.077,32.8005);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AASA4IgCgBIgBgCIgTgmIgCABIgKgBIAAAmIgBACIgCABIgUAAIgCgBIgBgCIAAhjQAAgDACgCQACgCADAAQALgCATAAIARACQAIACAGAEQAFADAFAIQADAIAAAIIAAACQAAALgFAHQgFAHgJAEIAWAqIABABQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgQghIAAAdIAKAAQALAAAEgDQAFgDAAgIIAAgCQAAgHgFgDQgFgDgJAAg");
	this.shape_5.setTransform(65.3769,32.6755);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgLA3QgGAAgFgFQgGgDgCgHQgDgGAAgJIAAgxQAAgNAFgGQAFgIAHgCQAHgCALAAIAdACQABAAAAAAQABAAAAAAQABABAAAAQAAABAAAAIAAAOIgBACIgCABIgfAAQgDAAgDACQgCACAAAGIAAAOIAlAAIADABIABACIAAANIgBACIgDABIglAAIAAAQQAAAEACADQACADAEAAIAfAAIACABIABACIAAAOQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgdABQgHABgGgCg");
	this.shape_6.setTransform(55.8517,32.7505);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglAyQgMgIAAgPIAAgBQABgGACgFQADgHADgCIALgIIgBgBIgLgPQgCgGAAgEIAAgCQAAgMAJgGQAIgIASABQARgBAHAIQAJAGAAAMIAAACQAAAGgDAEQgCAFgEAEIgPAKIATAUIACgHIAAgMIABgCIADAAIANAAIACAAIABACIAAABQAAAKgCAHQgBAGgGAKIAPAQIABABQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgUAAIgDgBIgEgFQgNAIgOgBQgSAAgMgGgAgWASQgCAEAAAEIAAABQAAAGAEADQAFADAIAAQAIAAAFgDIgVgZQgFAEgCADgAgRgkQgEACAAAEIAAACQAAADABADQADAEAEAEIABACIAFgDIAIgGQACgEAAgDIAAgCQAAgEgDgCQgBgDgHAAQgHAAgCADg");
	this.shape_7.setTransform(110.8026,15.8502);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASA4IgCgBIgUgoIgMAAIAAAmIgBACIgCABIgUAAIgCgBIgBgCIAAhjQAAgEACgBIAFgCQANgCARAAIARACQAIABAGAFQAGADAEAIQADAHAAAJIAAACQAAALgFAHQgGAIgIACIAWAqIABACQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgQghIAAAdIAKAAQALAAAEgDQAFgDAAgIIAAgCQAAgHgFgDQgFgDgJAAIgLAAg");
	this.shape_8.setTransform(98.0774,15.7752);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLA3QgHgBgEgDQgFgEgDgGQgDgGAAgKIAAgxQAAgMAFgIQAFgGAIgEQAGgBALAAIAdABQABAAABABQAAAAAAAAQABABAAAAQAAABAAAAIAAAOIAAACIgDABIgeAAQgFAAgCACQgCACABAGIAAAOIAlAAIACABIABABIAAAOIgBACIgCAAIglAAIAAARQgBAGACACQACACAFAAIAeAAIADABIAAABIAAAPQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgdACQgGAAgHgBg");
	this.shape_9.setTransform(88.5022,15.8502);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAVA3IgCAAIgBgDIAAgrIgkAAIAAArIAAADIgCAAIgUAAIgCAAIgBgDIAAhnIABgCIACgBIAUAAIACABIAAACIAAAnIAkAAIAAgnIABgCIACgBIAUAAIACABIABACIAABnIgBADIgCAAg");
	this.shape_10.setTransform(78.7021,15.8252);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgGA2QgHgCgIgGQgFgGgEgJQgEgJABgNIAAgSQgBgNAEgIQAEgKAFgFQAHgFAIgEQAGgBAKAAIANAAIAIACQABAAABABQAAAAABAAQAAABAAAAQAAABAAAAIAAAOQAAABAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIgBAAIgVgBQgHAAgDACQgDADgCAFQgDAHAAAIIAAASQAAAJADAGQACAGADACQAEACAGABIAWgCQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAPIAAACIgDABQgIACgNAAQgJAAgHgCg");
	this.shape_11.setTransform(69.202,15.8502);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJA3IgCAAIgBgDIAAhnIABgCIACgBIATAAIACABIABACIAABnIgBADIgCAAg");
	this.shape_12.setTransform(62.6269,15.8252);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeA1QgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIAAgOQAAgBABgBQAAAAAAAAQABgBAAAAQABAAABAAIAcACQAHgBACgCQADgCAAgGQAAgDgCgDQgBgCgHgDIgTgNQgHgCgDgFQgEgFgCgEQgBgFgBgGQAAgMAJgJQAJgHATAAIASABIAOABQAAABABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAAPQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgYgBIgIAAQgEAAgEACQgCACAAAEQAAAEABABIAaAPQAKAGACACQAFAGABAEQACAIAAAEQAAAGgCAGQgDAGgEAEQgEAFgJACQgIADgJAAQgQABgMgEg");
	this.shape_13.setTransform(55.9517,15.8502);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#D70A2D").s().p("AhiCfQgKAAgHgIQgIgHAAgKIAAiGQAAgJAIgIQAHgHAKAAIAKAAIAAgtQAAglAagaQAagaAkAAQAkAAAbAaQAaAaAAAlIAAAtIAJAAQALAAAHAHQAIAIAAAJIAACGQAAAKgIAHQgHAIgLAAgAALBwIgCgeIACgDQAMgGAAgOQAAgKgHgGQgHgHgJABQgJgBgGAHQgHAGAAAKQAAAOAMAGIABADIgBAeIAVAAgAgmhtQgRAQAAAYIAAAtIBvAAIAAgtQAAgYgRgQQgQgQgXAAQgWAAgQAQg");
	this.shape_14.setTransform(21.5512,22.2003);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhqDFQhrhFAAh3IAAikQAAgQAHgKQAIgMANgDICxgtQAIgCAJACICLAkIAlAJQAOADAIAMQAHAKAAAQIAACkQAAByhrBHQghAWgpAQIghALQg1gLg1gjg");
	this.shape_15.setTransform(21.4262,24.3129);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_icn_sicher_erlaubt, new cjs.Rectangle(0,0,115.9,48.6), null);


(lib.mc_icn_18plus = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D70A2D").s().p("AAMBtIAAizIgBAAIglAsIgTgZIAyg5IApAAIAADZg");
	this.shape.setTransform(7.6001,24.7004);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D70A2D").s().p("AgCBvQgqAAgNgJQgNgLAAgiIAAgGQAAgcAGgMQAGgLARgCIAAgBQgQgCgFgKQgHgKAAgaIAAgGQAAgiANgKQANgJApAAIAFAAQAqAAAMAJQANAKAAAiIAAAGQAAAagGAKQgGAJgRADIAAABQASACAGALQAHAMAAAcIAAAGQAAAigOALQgMAJgrAAgAgfARQgHAFAAAUIAAAIQAAAUAHAFQAGAFAZAAIACAAQAYAAAGgFQAHgFAAgUIAAgIQAAgUgHgFQgGgFgYAAIgCAAQgZAAgGAFgAgfhLQgFAFAAASIAAAGQgBATAGAFQAGAFAZAAIACAAQAYAAAGgFQAFgFABgTIAAgGQAAgSgHgFQgFgGgYAAIgCAAQgYAAgHAGg");
	this.shape_1.setTransform(21.8003,24.7254);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D70A2D").s().p("AgQBYIAAhHIg8AAIAAgjIA8AAIAAhFIAhAAIAABFIA8AAIAAAjIg8AAIAABHg");
	this.shape_2.setTransform(38.1506,24.6504);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiqCsQhHhHgBhlQABhjBHhHQBGhIBkABQBlgBBGBIQBHBHABBjQgBBlhHBHQhGBHhlAAQhkAAhGhHgAhQhgQgNAKAAAiIAAAFQAAAbAGAJQAFAKARACIAAABQgRADgGALQgHAMAAAcIAAAGQAAAiAOALQANAJAqAAIAGAAQApAAANgJQANgLAAgiIAAgGQAAgcgHgMQgGgLgRgDIAAgBQARgCAFgKQAHgJgBgbIAAgFQABgigNgKQgNgJgoAAIgGAAQgqAAgMAJgAiZhCIAACzIAiAAIAAjZIgqAAIgzA5IATAZIAngsgAA+AVIA8AAIAABHIAiAAIAAhHIA8AAIAAgjIg8AAIAAhFIgiAAIAABFIg8AAgAgZBVQgYAAgGgFQgHgFAAgUIAAgIQAAgUAHgFQAGgFAYAAIADAAQAYAAAGAFQAHAFAAAUIAAAIQAAAUgHAFQgGAFgYAAgAgZgNQgYAAgGgEQgGgGAAgSIAAgHQAAgSAGgEQAHgGAXAAIADAAQAXAAAGAGQAGAEAAASIAAAHQAAATgFAFQgHAEgXAAg");
	this.shape_3.setTransform(24.2504,24.2504);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_icn_18plus, new cjs.Rectangle(0,0,48.5,48.5), null);


(lib.mc_hl1_txt5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVAfQgDAAgCgCQgDgCAAgDIAAgvQAAgDADgCQACgCADAAIArAAQADAAADACQACABAAAEIAAAvQAAADgCACQgDACgDAAg");
	this.shape.setTransform(51.5,15.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AghBrQgSgFgNgMQgNgLgJgTQgIgTAAgbIAAgZQAAgfALgWQAMgXAWgMQAWgMAcAAQAeAAAWANQAVANALAWQAKAXAAAdIAAAVQAAAJgIAAIh4AAIAAABQAAApAmAAIAmgBIAjgCIABAAQAHAAAAAGIAAAdQAAAEgBADQgCACgFABQgkAJgpAAQgSAAgQgFgAgXgzQgKALAAAVIAAABIBEAAIAAgBQAAgVgJgLQgJgLgQAAQgQAAgIALg");
	this.shape_1.setTransform(35.1,7.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABZBvQgDAAgCgDQgCgCAAgDIAAiBQAAgSgFgHQgFgGgNAAQgPgBgOAIIABAYIAACBQAAADgDACQgCADgDAAIgtAAQgDAAgDgDQgCgCAAgDIAAiBQAAgSgEgHQgFgGgNAAQgKgBgTAKIAACXQAAADgCACQgCADgDAAIguAAQgEAAgCgDQgCgCAAgDIAAjKQAAgDACgCQACgDADAAIArAAQAEAAACADQACACAAADIAAAJQAcgUAcAAQAPABAMAEQAKAEAHAKQASgKANgEQANgEASgBQAYAAAPALQAOAKAGASQAGATAAAaIAACBQAAADgCACQgCADgEAAg");
	this.shape_2.setTransform(7.275,7.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWCTQgDAAgDgDQgCgCAAgDIAAjKQAAgDACgCQADgDADAAIAtAAQADAAACADQADACAAADIAADKQAAADgDACQgCADgDAAgAgYhfQgDAAgCgCQgCgCAAgDIAAgkQAAgDACgDQACgCADAAIAxAAQADAAACACQACACAAAEIAAAkQAAADgCACQgCACgDAAg");
	this.shape_3.setTransform(-14.825,3.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYCNQgDAAgCgCQgDgCABgDIAAjdIg/AAQgCAAgDgCQgCgCAAgDIAAgnQAAgDACgCQADgCACAAIC8AAQADAAADACQACACAAADIAAAnQAAADgCACQgDACgDAAIg+AAIAADdQAAADgBACQgDACgDAAg");
	this.shape_4.setTransform(-31.5,4.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_hl1_txt5, new cjs.Rectangle(-44.6,-23.2,103.5,51.599999999999994), null);


(lib.mc_hl1_txt4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkBQIgMgCIgEgBIAAgCIAAgRIAAgDIADgCIABAAIANACIANAAQAGAAADgDQAEgCABgGIACgGIgDAAQgHAAgFgEQgEgDgDgNIgdheIAAgBQABgEAEAAIAbAAQADABABAEIAUBOQAAABAAAAQAAABABAAQAAABAAAAQAAAAAAAAIABAAIABAAIAThRQABgEAEgBIAcAAIACACIABADIAAAAIAAAAIgjB7QgDANgFAHQgFAHgJAEQgHAEgQAAIgNgCg");
	this.shape.setTransform(34.95,1.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AACBJQgFgCgFgEQgEgEgCgHQgCgIgBgKIAAg8IgRgDIgCgBIgBgDIAAgOIABgDIACgCIARAAIAAgQQAAgEAEgBIAZgEIABAAIADABIABACIAAAWIARAAIADACIABADIAAARIgBADIgDABIgRAAIAAA8IABAHQAAAAAAAAQAAABAAAAQAAABAAAAQABAAAAAAIAFABIAKAAQAFAAgBAEIAAAQQAAADgDABQgKACgHAAQgJAAgHgBg");
	this.shape_1.setTransform(24.25,-1.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMBRIgCgBIgCgDIAAhvIACgDQAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIAZAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIACADIAABvIgCADIgCABgAgNg0IgCgBIgCgDIAAgUQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAABAAQAAAAAAAAIAaAAIAEABQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAAAIAAAUIgBADIgEABg");
	this.shape_2.setTransform(16.85,-2.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgMBQIgCgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAiXIACgDIACgCIAZAAIADACIABADIAACXIgBADQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(10.8,-2.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglA1QgLgJABgSIAAgCQAAgSAMgIQAMgIAaAAIAMAAIAAgIQgBgJgEgCQgDgDgHgBQgUAAgPACIgBAAQgEAAAAgEIAAgRQAAgDAEgBQATgFARAAQAXAAANAKQAMAKAAAXIAABKIgBADIgDABIgYAAIgCgBIgBgDIAAgDQgHAEgHADQgGACgIAAQgQAAgKgJgAgKAMQgFAEAAAIIAAACQAAAGAEACQADADAHgBQAGAAAKgEIAAgYIgMAAQgKABgDADg");
	this.shape_4.setTransform(1.75,-0.75);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggA5QgHgDgEgHQgEgFgCgJQgCgJAAgLIAAhFIACgDIADgBIAZAAIADABIABADIAABFQAAAMADAEQAEAEAJAAIAIgCIALgEIAAhTIABgDIADgBIAZAAIADABIACADIAABwIgCACIgCABIgYAAIgDgBIgBgCIAAgGQgIAGgIACQgHADgLAAQgKAAgIgEg");
	this.shape_5.setTransform(-10.375,-0.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAABfQgHgDgEgIQgFgHAAgMIAAgFQgKgCgIgFQgIgEgGgIQgGgJgEgLQgDgMAAgNIAAgZQAAgjARgQQARgRAbAAQAOAAALAEQALAEAJAIQAIAIAFANQAEANAAASIAAAZQAAASgFAOQgGAOgKAIQgKAIgOACIAAAFIABAEIAEABIATAAQAFAAAAADIAAARQAAAEgFABQgLADgMAAQgKAAgIgDgAgNg9QgGADgDAIQgDAIAAANIAAAZQAAALADAIQADAIAFAEQAGAEAIAAQANAAAHgJQAGgJAAgRIAAgZQAAgTgGgJQgHgIgNAAQgIAAgFAEg");
	this.shape_6.setTransform(-24.125,-0.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_hl1_txt4, new cjs.Rectangle(-33.4,-18.5,76.8,30.3), null);


(lib.mc_hl1_txt3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVAvIgCgBIgBgDIAAhUIABgCIACgBIATAAIACABIAAACIAAADQAFgEAFgBQAGgDAGAAIACABIABADIAAAPIgBACIgBABIgCAAQgKAAgKAFIAAA+IgBADIgBABg");
	this.shape.setTransform(-25.625,3.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYA7QgGgCgDgFQgDgFgBgGQgCgHAAgIIAAg1IABgCIADgBIAUAAIABABIABACIAAA1QABAIACAEQACADAIAAIAFgBIAIgFIAAg+IABgCIADgBIATAAIACABIABACIAABVIgBACIgCABIgSAAIgCgBIgBgCIAAgEQgHAEgGACQgEACgIAAQgJAAgFgDgAAKgoIgCgBIgCgDIAAgOIACgCIACgCIAPAAIADACIABACIAAAOQAAABgBAAQAAABAAAAQAAAAAAAAQgBABAAAAIgCABgAgYgoIgCgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAgBIAAgOIABgCIACgCIAPAAIADACIAAACIAAAOIAAADIgDABg");
	this.shape_1.setTransform(-34,2.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgJA+IgCgBIgBgCIAAhFIgNgBIgCgBIgBgCIAAgMIABgCIACgBIANAAIAAgFQAAgQAGgGQAGgFAOAAIAMABQABAAABAAQAAABAAAAQABABAAAAQAAABAAABIAAAMQAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIgIAAIgDAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAFIAAAFIANAAIACABIABACIAAAOIgBABIgCABIgNAAIAABFIgBACIgCABg");
	this.shape_2.setTransform(-42.325,2.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_hl1_txt3, new cjs.Rectangle(-47.7,-10.3,27.200000000000003,24), null);


(lib.mc_hl1_txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkBuQgSgCgQgEQgHgCAAgHIAAgfQAAgDACgCQACgCADAAIACAAIAnAEIAZABQAMAAAFgDQAFgEgBgHQAAgFgCgDQgEgEgHgEIgxgdQgPgIgKgOQgIgPgBgSQAAgTAJgOQAIgNASgGQARgHAaAAQAOAAALABQAMABAJACIAVAFQAHABAAAHIAAAfQAAAHgGAAIgBAAIgggDQgTgCgMAAQgKAAgFADQgFACAAAHQAAADADADIAJAHIAuAbQAXAMAHAOQAJAOgBARQABAcgVASQgUASgoAAQgQAAgTgCg");
	this.shape.setTransform(29.95,5.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAECDQgKgCgIgIQgIgHgEgNQgFgNAAgTIAAhuIgegEQgDAAgDgDQgCgCAAgDIAAgZQAAgEACgCQADgCADgBIAeAAIAAgeQABgHAHgBIAtgIIABAAQADAAADACQAAAAAAABQABAAAAABQAAAAAAABQABABAAABIAAAnIAfAAQACABADACQACADAAACIAAAfQAAADgCACQgDACgCAAIgfAAIAABvIAAALQACAEACABQACACAGAAIATAAQAIAAAAAFIAAAfQAAAGgHABQgTADgMAAQgQAAgMgDg");
	this.shape_1.setTransform(12.25,3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgyBkQgWgMgLgWQgLgXAAgeIAAgZQAAgeALgWQALgXAWgMQAVgMAdAAQAuAAAZAaQAYAbAAAuIAAAZQAAAugYAbQgZAaguAAQgdAAgVgMgAgYgvQgJAMAAAXIAAAZQAAAXAJAMQAJAMAPAAQARAAAJgMQAIgMAAgXIAAgZQAAgXgIgMQgJgMgRAAQgPAAgJAMg");
	this.shape_2.setTransform(-6.825,5.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWCSQgDAAgDgDQgCgCAAgDIAAkTQAAgDADgCQACgDADAAIAtAAQADAAADADQACACAAADIAAETQAAADgCACQgCADgEAAg");
	this.shape_3.setTransform(-23.325,1.475);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhPCIQgHgCAAgGIAAglQAAgHAGAAIACAAIAmADIAiACQASAAAHgHQAHgGAAgOQAAgIgFgHQgFgFgPgJIgzgfQgRgJgKgLQgKgMgEgNQgEgNAAgOQAAgiAXgUQAWgTAzgBQAVABAZACQAYADALACQAGACAAAGIAAAmQAAAGgHAAIgBAAIgRgBIgRgBIgYgCIgWAAQgPAAgHAFQgHAFAAALQAAAHAFAFQAFAFAQAJIAvAaQATAKAMALQALAMAFAOQAFANAAAQQAAAQgGAPQgGAOgMAMQgMAMgUAHQgVAIgagBQgoAAgggIg");
	this.shape_4.setTransform(-39.875,1.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_hl1_txt2, new cjs.Rectangle(-53,-25.3,94.7,51.6), null);


(lib.mc_hl1_txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglBRIgLgDIgEgCIgBgCIAAgRIABgCIAEgBIAAAAIAMABIAPAAQAFAAAEgCQADgDABgGIACgGIgDAAQgHgBgEgDQgFgDgEgNIgbheIAAgBQAAgEADABIAcAAQAEAAABADIASBPQABAAAAABQAAABABAAQAAABAAAAQAAAAAAAAIABAAIABAAIAUhSQAAgDAEAAIAbAAIAEABIABACIAAABIAAAAIgkB7QgDAMgFAIQgFAHgJAEQgIADgPABIgOgBg");
	this.shape.setTransform(6.1,4.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AADBIQgGgBgFgEQgEgEgCgHQgDgHAAgLIAAg8IgQgDIgEgBIgBgDIAAgOIABgDIAEgBIAQAAIAAgRQABgEAEgBIAZgEIAAAAIADABIABACIAAAXIARAAIADABIABADIAAARIgBADIgDABIgRAAIAAA8IAAAGQAAABABAAQAAABAAAAQAAABAAAAQABAAAAAAIAEABIALAAQAFAAAAAEIAAAQQAAADgFABQgKACgGAAQgJAAgGgCg");
	this.shape_1.setTransform(-4.6,1.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMBRIgDgBIgBgDIAAhvIABgDQABAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAZAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABABAAIABADIAABvIgBADIgDABgAgMg0IgEgBIgBgDIAAgTQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAaAAIACABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAATIgCADIgCABg");
	this.shape_2.setTransform(-12,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgLBRIgEgCQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAiYIABgCIAEgBIAYAAIADABIABACIAACYIgBADQAAAAgBABQAAAAAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_3.setTransform(-18.05,0.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglA1QgLgIAAgTIAAgCQAAgTAMgHQANgJAaAAIALAAIAAgHQAAgJgDgDQgEgCgIAAQgTAAgPABIgBAAQgEAAAAgEIAAgRQAAgDAEgCQASgEASAAQAXAAAMALQANAJABAXIAABKIgCADIgDABIgXAAIgDgBIgCgDIAAgEQgGAFgHADQgGACgJAAQgPAAgKgJgAgLAMQgDADAAAJIAAACQAAAGACACQAEACAHAAQAGAAAKgEIAAgYIgMAAQgKAAgEAEg");
	this.shape_4.setTransform(-27.1,2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggA5QgHgDgEgHQgEgFgCgJQgCgJAAgLIAAhEIACgEIADgBIAZAAIADABIABAEIAABEQAAALADAFQAEAEAJAAIAIgCIALgEIAAhSIABgEIADgBIAZAAIADABIACAEIAABuIgCADIgCACIgYAAIgDgCIgBgDIAAgEQgIAFgIACQgHADgLAAQgKAAgIgEg");
	this.shape_5.setTransform(-39.225,2.65);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAABfQgHgDgEgIQgFgHAAgMIAAgFQgKgCgIgFQgIgEgGgIQgGgJgEgLQgDgMAAgNIAAgZQAAgjARgQQARgRAbAAQAOAAALAEQALAEAJAIQAIAIAFANQAEANAAASIAAAZQAAASgFAOQgGAOgKAIQgKAIgOACIAAAFIABAEIAEABIATAAQAFAAAAADIAAARQAAAEgFABQgLADgMAAQgKAAgIgDgAgNg9QgGADgDAIQgDAIAAANIAAAZQAAALADAIQADAIAFAEQAGAEAIAAQANAAAHgJQAGgJAAgRIAAgZQAAgTgGgJQgHgIgNAAQgIAAgFAEg");
	this.shape_6.setTransform(-52.975,2.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_hl1_txt1, new cjs.Rectangle(-62.3,-15.2,76.8,30.4), null);


(lib.mc_hl1_shadow = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap11111111111111111();
	this.instance.setTransform(-119,-77);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_hl1_shadow, new cjs.Rectangle(-119,-77,198,112), null);


(lib.mc_device2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.hpa_slots_quali_device2();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_device2, new cjs.Rectangle(0,0,400,553), null);


(lib.mc_device = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.hpa_slots_quali_device();
	this.instance.setTransform(-200,-272);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_device, new cjs.Rectangle(-200,-272,400,544), null);


(lib.mc_cta_inner = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D70A2D").s().p("AAPAsIgCgBIAAgDIAAgwQAAgJgCgCQgDgEgGAAQgFABgJAFIAAA5IgBADIgBABIgTAAIgCgBIgBgDIAAhOIABgDIACgBIARAAIACABIABADIAAADQAGgEAFgCQAFgBAHgBQAPAAAGAJQAGAKAAAQIAAAwIgBADIgDABg");
	this.shape.setTransform(40.95,0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D70A2D").s().p("AgMAqQgHgCgFgFQgGgEgDgIQgEgHAAgKIAAgKQABgMAFgJQAEgJAIgFQAJgEALAAQALAAAJAFQAJAFADAJQAFAJAAALIAAAIQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIguAAIAAABQAAAQAOAAIAPAAIAOgBIAAAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALIgBADIgCABQgOAEgQAAQgHAAgGgCgAgJgUQgDAFAAAIIAAAAIAaAAIAAAAQAAgIgDgFQgEgEgGAAQgGAAgEAEg");
	this.shape_1.setTransform(31.95,0.475);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D70A2D").s().p("AgIA6IgCgBIgBgDIAAhsIABgCIACgBIARAAIACABIABACIAABsIgBADIgCABg");
	this.shape_2.setTransform(25.425,-1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#D70A2D").s().p("AgNAqQgGgCgFgFQgGgEgDgIQgEgHAAgKIAAgKQABgMAFgJQAEgJAIgFQAJgEALAAQALAAAJAFQAJAFADAJQAFAJAAALIAAAIQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIguAAIAAABQAAAQAOAAIAPAAIAOgBIAAAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALIgBADIgCABQgOAEgQAAQgHAAgHgCgAgJgUQgDAFAAAIIAAAAIAaAAIAAAAQAAgIgDgFQgEgEgGAAQgGAAgEAEg");
	this.shape_3.setTransform(18.9,0.475);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#D70A2D").s().p("AgIA6IgCgBIgBgCIAAhPIABgCIACgBIARAAIACABIABACIAABPIgBACIgCABgAgJglIgCgBIgBgCIAAgOIABgCIACgBIATAAIACABIABACIAAAOIgBACIgCABg");
	this.shape_4.setTransform(12.325,-1.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#D70A2D").s().p("AghA6IgCgBIgBgCIAAhoIABgDIADgCIAQgCIAQgBQAIAAAHADQAHACAFAFQAFAFADAHQACAHAAAJIAAAMQAAALgEAIQgEAJgJAFQgIAEgMAAIgMgBIAAAaIgBACIgCABgAgMgkIAAAtIAMABQAEABADgDQADgCACgFIABgIIAAgMQAAgIgDgGQgDgEgHAAIgGAAIgGABg");
	this.shape_5.setTransform(5.825,1.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#D70A2D").s().p("AgOArIgNgCQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAgMIABgCIACgBIABAAIAPACIAKAAIAGgBQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAIgBgEIgFgDIgSgLQgGgDgEgFQgDgGAAgHQAAgIADgFQADgFAHgDQAHgCAKAAIAKAAIAIABIAIACQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAIAAANQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIAAAAIgNgBIgMAAIgFAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIABACIAEADIARALQAJAEADAFQADAGAAAHQAAALgIAHQgIAHgPAAIgOgBg");
	this.shape_6.setTransform(-2.575,0.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#D70A2D").s().p("AACA0QgEgCgDgCQgDgDgCgFQgBgFgBgIIAAgrIgLgBIgCgBIgBgCIAAgKIABgDIACgBIALAAIAAgLQAAgBABgBQAAAAAAAAQABgBAAAAQABAAABAAIARgEIABAAIACABIAAABIAAAQIAMAAIADABIABADIAAAMIgBACIgDAAIgMAAIAAArIAAAFIABACIAEABIAHAAQABAAABAAQAAAAABAAQAAAAAAABQABAAAAABIAAALQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBABIgLABIgLgBg");
	this.shape_7.setTransform(-13.4,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#D70A2D").s().p("AgaArQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIAAgJQAAgEACgCIAfgsIABgBIgBAAIgdAAIgCgBIgBgCIAAgOIABgCIACgBIA2AAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAIAAAMIgCAEIgeAqIAAABIAAABIAdAAIACAAIABACIAAAPIgBACIgCABg");
	this.shape_8.setTransform(-20.375,0.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#D70A2D").s().p("AACA0QgEgCgDgCQgDgDgCgFQgBgFAAgIIAAgrIgNgBIgCgBIgBgCIAAgKIABgDIACgBIANAAIAAgLQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIASgEIAAAAIACABIABABIAAAQIANAAIABABIABADIAAAMIgBACIgBAAIgNAAIAAArIAAAFIACACIADABIAIAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAALQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAABIgMABIgLgBg");
	this.shape_9.setTransform(-27.4,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#D70A2D").s().p("AgMAqQgHgCgFgFQgGgEgDgIQgDgHgBgKIAAgKQAAgMAGgJQAEgJAIgFQAJgEAKAAQANAAAIAFQAJAFADAJQAEAJABALIAAAIQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIguAAIAAABQAAAQAOAAIAPAAIAOgBIABAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALIgBADIgCABQgOAEgRAAQgGAAgGgCgAgJgUQgDAFAAAIIAAAAIAaAAIAAAAQAAgIgDgFQgEgEgHAAQgFAAgEAEg");
	this.shape_10.setTransform(-34.75,0.475);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#D70A2D").s().p("AgQBEQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgPQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAIAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBIABgEIAAhsIABgCIACgBIASAAIADABIAAACIAABsQAAAOgHAGQgHAGgLAAIgKgBg");
	this.shape_11.setTransform(-42.125,0.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_2
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AnRCmQgjAAgagZQgZgaAAgiIAAigQAAgjAZgaQAZgZAkAAIOkAAQAjAAAZAZQAZAZAAAkIAACgQAAAjgZAZQgZAZgjAAg");
	this.shape_12.setTransform(0.475,-0.05);

	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_cta_inner, new cjs.Rectangle(-54.7,-16.6,110.4,33.2), null);


(lib.mc_asset1_inner = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.hpa_slots_quali_asset1();
	this.instance.setTransform(-20,-53);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_asset1_inner, new cjs.Rectangle(-20,-53,400,206), null);


(lib.logo_bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D70A2D").s().p("AyPVmQoahymgjQQmfjPjjkNQjskXAAkxQAAkwDskXQDjkNGfjPQGgjQIahyQIuh2JhAAQJiAAIuB2QIaByGfDQQGgDPDjENQDsEXAAEwQAAExjsEXQjjENmgDPQmfDQoaByQouB2piAAQphAAouh2g");
	this.shape.setTransform(0.0046,0.0273);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logo_bg, new cjs.Rectangle(-300,-149.9,600,299.9), null);


(lib.btn_clicktag = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(150,300);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.mc_logo_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_749 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(749).call(this.frame_749).wait(1));

	// Logos
	this.instance = new lib.mc_logo();
	this.instance.setTransform(54.6,29.5,0.6857,0.6855,0,0,0,0.3,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(750));

	// Logo BG Vertical
	this.instance_1 = new lib.logo_bg();
	this.instance_1.setTransform(0,0,0.4476,0.4476);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-5.9972},125).to({rotation:5.9972},249).to({rotation:0},125).to({rotation:-5.9975},125).to({rotation:0},125).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140.5,-80.8,281.1,161.7);


(lib.mc_icn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 18+ Sicher & Erlaubt
	this.instance = new lib.mc_icn_sicher_erlaubt();
	this.instance.setTransform(-57.65,-24.3,1,1,0,0,0,58,24.3);

	this.instance_1 = new lib.mc_icn_18plus();
	this.instance_1.setTransform(-150.05,-24.3,1,1,0,0,0,24.2,24.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mc_icn, new cjs.Rectangle(-174.2,-48.6,174.5,48.6), null);


(lib.mc_hl1_ani = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_57 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(57).call(this.frame_57).wait(1));

	// txt5
	this.instance = new lib.mc_hl1_txt5();
	this.instance.setTransform(148.75,3.15);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(17).to({_off:false},0).to({x:14.1},11,cjs.Ease.cubicOut).wait(30));

	// txt4
	this.instance_1 = new lib.mc_hl1_txt4();
	this.instance_1.setTransform(-72.3,171.95);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(13).to({_off:false},0).to({x:-73.7,y:-0.55},11,cjs.Ease.cubicOut).wait(34));

	// txt3
	this.instance_2 = new lib.mc_hl1_txt3();
	this.instance_2.setTransform(153.55,-34.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:50.2},11,cjs.Ease.cubicOut).wait(38));

	// txt2
	this.instance_3 = new lib.mc_hl1_txt2();
	this.instance_3.setTransform(-184.6,-31.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(5).to({_off:false},0).to({x:-38.3},11,cjs.Ease.cubicOut).wait(42));

	// txt1
	this.instance_4 = new lib.mc_hl1_txt1();
	this.instance_4.setTransform(-43.45,-172.85);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({_off:false},0).to({y:-57.85},11,cjs.Ease.cubicOut).wait(46));

	// HL Shadow
	this.instance_5 = new lib.mc_hl1_shadow();
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({_off:false},0).to({alpha:0.3711},24).wait(33));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-237.6,-188,445.29999999999995,371.8);


(lib.mc_cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {anim:4};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(20));

	// Layer_1
	this.instance = new lib.mc_cta_inner();
	this.instance.setTransform(-0.25,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({scaleX:1.2,scaleY:1.2,x:-0.3,y:-0.05},3).to({scaleX:1,scaleY:1,x:-0.25,y:0},12).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66,-20,132.6,39.8);


(lib.mc_asset_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.mc_asset1_inner();
	this.instance.setTransform(20,53,1,1,-12.2283);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0.1,regY:0.1,rotation:5.9724,x:20.1,y:53.05},74,cjs.Ease.cubicInOut).to({regX:0,regY:0,rotation:-12.2276,x:20,y:53},75,cjs.Ease.cubicInOut).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.8,-79.3,439.6,324);


// stage content:
(lib._300x600_halfpagead = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {loop:1};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,149,179,209,234,259];
	// timeline functions:
	this.frame_0 = function() {
		if(!this.listenersSet || typeof this.listenersSet == "undefined") {
			this.listenersSet = true;
			
			// BIND BUTTON ACTIONS & CO
			window.animationStage = this;
			this.looper = 1;	//nicht anfassen
			this.maxLoops = 2;	//diese Variable setzen für die Anzahl der Abläufe
		}
		this.btn_clicktag.addEventListener("click", window.callClicktag);
		
		/*
		this.btn_clicktag1.addEventListener("click", function (evt) {
				window.callClicktag(evt, "1");
		});
		*/
	}
	this.frame_149 = function() {
		this.mc_cta.gotoAndPlay('anim');
	}
	this.frame_179 = function() {
		this.mc_cta.gotoAndPlay('anim');
	}
	this.frame_209 = function() {
		this.mc_cta.gotoAndPlay('anim');
	}
	this.frame_234 = function() {
		if (this.looper < this.maxLoops) {
			this.looper++;
		} else {
			this.stop();
		}
	}
	this.frame_259 = function() {
		this.gotoAndPlay("loop");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(149).call(this.frame_149).wait(30).call(this.frame_179).wait(30).call(this.frame_209).wait(25).call(this.frame_234).wait(25).call(this.frame_259).wait(1));

	// clicktag
	this.btn_clicktag = new lib.btn_clicktag();
	this.btn_clicktag.name = "btn_clicktag";
	this.btn_clicktag.setTransform(0,0,1,1.0001);
	new cjs.ButtonHelper(this.btn_clicktag, 0, 1, 2, false, new lib.btn_clicktag(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_clicktag).wait(260));

	// logo anim
	this.instance = new lib.mc_logo_anim();
	this.instance.setTransform(0.8,0.8,1.3373,1.3373,0,0,0,0.2,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(260));

	// red_footer_bg (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EhdvBinMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_104 = new cjs.Graphics().p("EhdvBinMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_105 = new cjs.Graphics().p("EhdvBinMAABicbQAOJOHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpOMAABCcbg");
	var mask_graphics_106 = new cjs.Graphics().p("EhdvBimMAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_107 = new cjs.Graphics().p("EhdvBiiMAABicbQAOJOHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpOMAABCcbg");
	var mask_graphics_108 = new cjs.Graphics().p("EhdvBibMAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_109 = new cjs.Graphics().p("EhdvBiPMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpNMAABCcag");
	var mask_graphics_110 = new cjs.Graphics().p("EhdvBh+MAABicbQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_111 = new cjs.Graphics().p("EhdvBhlMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpNMAABCcag");
	var mask_graphics_112 = new cjs.Graphics().p("EhdvBhFMAABicbQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_113 = new cjs.Graphics().p("EhdvBgbMAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_114 = new cjs.Graphics().p("EhdvBfmMAABicaQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcag");
	var mask_graphics_115 = new cjs.Graphics().p("EhdvBenMAABicbQAOJOHJIcQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_116 = new cjs.Graphics().p("EhdvBdaMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpNMAABCcag");
	var mask_graphics_117 = new cjs.Graphics().p("EhdvBcDMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_118 = new cjs.Graphics().p("EhdvBa3MAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_119 = new cjs.Graphics().p("EhdvBZ3MAABicbQAOJOHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpOMAABCcbg");
	var mask_graphics_120 = new cjs.Graphics().p("EhdvBZDMAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_121 = new cjs.Graphics().p("EhdvBYZMAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_122 = new cjs.Graphics().p("EhdvBX4MAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_123 = new cjs.Graphics().p("EhdvBXgMAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_124 = new cjs.Graphics().p("EhdvBXOMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_125 = new cjs.Graphics().p("EhdvBXDMAABicbQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_126 = new cjs.Graphics().p("EhdvBW7MAABicaQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEgBQTEABRbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcag");
	var mask_graphics_127 = new cjs.Graphics().p("EhdvBW4MAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_128 = new cjs.Graphics().p("EhdvBW2MAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_129 = new cjs.Graphics().p("EhdvBW2MAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_234 = new cjs.Graphics().p("EhdvBW2MAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_235 = new cjs.Graphics().p("EhdvBW2MAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_236 = new cjs.Graphics().p("EhdvBW4MAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_237 = new cjs.Graphics().p("EhdvBW7MAABicaQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEgBQTEABRbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcag");
	var mask_graphics_238 = new cjs.Graphics().p("EhdvBXDMAABicbQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_239 = new cjs.Graphics().p("EhdvBXOMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_240 = new cjs.Graphics().p("EhdvBXgMAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_241 = new cjs.Graphics().p("EhdvBX4MAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_242 = new cjs.Graphics().p("EhdvBYZMAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_243 = new cjs.Graphics().p("EhdvBZDMAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_244 = new cjs.Graphics().p("EhdvBZ3MAABicbQAOJOHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpOMAABCcbg");
	var mask_graphics_245 = new cjs.Graphics().p("EhdvBa3MAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_246 = new cjs.Graphics().p("EhdvBcDMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");
	var mask_graphics_247 = new cjs.Graphics().p("EhdvBdaMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpNMAABCcag");
	var mask_graphics_248 = new cjs.Graphics().p("EhdvBenMAABicbQAOJOHJIcQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_249 = new cjs.Graphics().p("EhdvBfmMAABicaQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcag");
	var mask_graphics_250 = new cjs.Graphics().p("EhdvBgbMAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_251 = new cjs.Graphics().p("EhdvBhFMAABicbQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_252 = new cjs.Graphics().p("EhdvBhlMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpNMAABCcag");
	var mask_graphics_253 = new cjs.Graphics().p("EhdvBh+MAABicbQAOJNHJIdQHHIaM+GfQM/GfQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/mfQM+mfHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_254 = new cjs.Graphics().p("EhdvBiPMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpNMAABCcag");
	var mask_graphics_255 = new cjs.Graphics().p("EhdvBibMAABicbQAOJOHJIcQHHIaM+GgQM/GfQ1DjQRaDsTEAAQTEAARbjsQQ1jjM/mfQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_256 = new cjs.Graphics().p("EhdvBiiMAABicbQAOJOHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpOMAABCcbg");
	var mask_graphics_257 = new cjs.Graphics().p("EhdvBimMAABicbQAOJOHJIcQHHIaM+GgQM/GeQ1DkQRaDsTEAAQTEAARbjsQQ1jkM/meQM+mgHHoaQHJocAOpOMAABCcbg");
	var mask_graphics_258 = new cjs.Graphics().p("EhdvBinMAABicbQAOJOHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJocAOpOMAABCcbg");
	var mask_graphics_259 = new cjs.Graphics().p("EhdvBinMAABicaQAOJNHJIcQHHIbM+GfQM/GfQ1DkQRaDrTEAAQTEAARbjrQQ1jkM/mfQM+mfHHobQHJobAOpOMAABCcag");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-5.5215,y:631.1264}).wait(104).to({graphics:mask_graphics_104,x:-5.5215,y:631.1264}).wait(1).to({graphics:mask_graphics_105,x:-5.5215,y:631.1071}).wait(1).to({graphics:mask_graphics_106,x:-5.5215,y:630.9721}).wait(1).to({graphics:mask_graphics_107,x:-5.5215,y:630.6059}).wait(1).to({graphics:mask_graphics_108,x:-5.5215,y:629.8926}).wait(1).to({graphics:mask_graphics_109,x:-5.5215,y:628.7168}).wait(1).to({graphics:mask_graphics_110,x:-5.5215,y:626.9626}).wait(1).to({graphics:mask_graphics_111,x:-5.5215,y:624.5144}).wait(1).to({graphics:mask_graphics_112,x:-5.5215,y:621.2566}).wait(1).to({graphics:mask_graphics_113,x:-5.5215,y:617.0736}).wait(1).to({graphics:mask_graphics_114,x:-5.5215,y:611.8496}).wait(1).to({graphics:mask_graphics_115,x:-5.5215,y:605.4689}).wait(1).to({graphics:mask_graphics_116,x:-5.5215,y:597.816}).wait(1).to({graphics:mask_graphics_117,x:-5.5215,y:589.1367}).wait(1).to({graphics:mask_graphics_118,x:-5.5215,y:581.4838}).wait(1).to({graphics:mask_graphics_119,x:-5.5215,y:575.1032}).wait(1).to({graphics:mask_graphics_120,x:-5.5215,y:569.8791}).wait(1).to({graphics:mask_graphics_121,x:-5.5215,y:565.6961}).wait(1).to({graphics:mask_graphics_122,x:-5.5215,y:562.4383}).wait(1).to({graphics:mask_graphics_123,x:-5.5215,y:559.9901}).wait(1).to({graphics:mask_graphics_124,x:-5.5215,y:558.236}).wait(1).to({graphics:mask_graphics_125,x:-5.5215,y:557.0601}).wait(1).to({graphics:mask_graphics_126,x:-5.5215,y:556.3468}).wait(1).to({graphics:mask_graphics_127,x:-5.5215,y:555.9806}).wait(1).to({graphics:mask_graphics_128,x:-5.5215,y:555.8456}).wait(1).to({graphics:mask_graphics_129,x:-5.5215,y:555.8264}).wait(105).to({graphics:mask_graphics_234,x:-5.5215,y:555.8264}).wait(1).to({graphics:mask_graphics_235,x:-5.5215,y:555.8456}).wait(1).to({graphics:mask_graphics_236,x:-5.5215,y:555.9806}).wait(1).to({graphics:mask_graphics_237,x:-5.5215,y:556.3468}).wait(1).to({graphics:mask_graphics_238,x:-5.5215,y:557.0601}).wait(1).to({graphics:mask_graphics_239,x:-5.5215,y:558.236}).wait(1).to({graphics:mask_graphics_240,x:-5.5215,y:559.9901}).wait(1).to({graphics:mask_graphics_241,x:-5.5215,y:562.4383}).wait(1).to({graphics:mask_graphics_242,x:-5.5215,y:565.6961}).wait(1).to({graphics:mask_graphics_243,x:-5.5215,y:569.8791}).wait(1).to({graphics:mask_graphics_244,x:-5.5215,y:575.1032}).wait(1).to({graphics:mask_graphics_245,x:-5.5215,y:581.4838}).wait(1).to({graphics:mask_graphics_246,x:-5.5215,y:589.1367}).wait(1).to({graphics:mask_graphics_247,x:-5.5215,y:597.816}).wait(1).to({graphics:mask_graphics_248,x:-5.5215,y:605.4689}).wait(1).to({graphics:mask_graphics_249,x:-5.5215,y:611.8496}).wait(1).to({graphics:mask_graphics_250,x:-5.5215,y:617.0736}).wait(1).to({graphics:mask_graphics_251,x:-5.5215,y:621.2566}).wait(1).to({graphics:mask_graphics_252,x:-5.5215,y:624.5144}).wait(1).to({graphics:mask_graphics_253,x:-5.5215,y:626.9626}).wait(1).to({graphics:mask_graphics_254,x:-5.5215,y:628.7168}).wait(1).to({graphics:mask_graphics_255,x:-5.5215,y:629.8926}).wait(1).to({graphics:mask_graphics_256,x:-5.5215,y:630.6059}).wait(1).to({graphics:mask_graphics_257,x:-5.5215,y:630.9721}).wait(1).to({graphics:mask_graphics_258,x:-5.5215,y:631.1071}).wait(1).to({graphics:mask_graphics_259,x:-5.5215,y:631.1264}).wait(1));

	// cta
	this.mc_cta = new lib.mc_cta();
	this.mc_cta.name = "mc_cta";
	this.mc_cta.setTransform(149.8,541.9);
	this.mc_cta.alpha = 0;
	this.mc_cta._off = true;

	var maskedShapeInstanceList = [this.mc_cta];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.mc_cta).wait(134).to({_off:false},0).to({y:519.45,alpha:1},12,cjs.Ease.cubicOut).wait(88).to({y:581.75,alpha:0},15,cjs.Ease.cubicIn).to({_off:true},1).wait(10));

	// SubHL 1
	this.instance_1 = new lib.mc_shl1();
	this.instance_1.setTransform(150,462.35);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(129).to({_off:false},0).to({y:444,alpha:1},12,cjs.Ease.cubicOut).wait(96).to({y:486.5,alpha:0},15,cjs.Ease.cubicIn).to({_off:true},1).wait(7));

	// 18+ Lotto
	this.instance_2 = new lib.mc_icn();
	this.instance_2.setTransform(285.85,591.85,0.5756,0.5758);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(260));

	// red_footer_bg
	this.instance_3 = new lib.mc_red_footer();
	this.instance_3.setTransform(-5.5,761.65,0.8581,0.8581);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(104).to({y:611.05},25,cjs.Ease.cubicInOut).wait(105).to({y:761.65},25,cjs.Ease.cubicInOut).wait(1));

	// device2
	this.instance_4 = new lib.mc_device2();
	this.instance_4.setTransform(158.6,369.75,0.9492,0.9492,0,0,0,200,276.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(99).to({_off:false},0).to({scaleX:0.6092,scaleY:0.6092,x:150,y:271.45,alpha:1},19,cjs.Ease.cubicInOut).wait(116).to({x:-148.95},19,cjs.Ease.cubicIn).to({_off:true},1).wait(6));

	// HL
	this.instance_5 = new lib.mc_hl1_ani();
	this.instance_5.setTransform(174.5,336.2,1.374,1.374,0,0,0,0.1,0.1);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(13).to({_off:false},0).wait(86).to({alpha:0},15).to({_off:true},1).wait(145));

	// asset1
	this.instance_6 = new lib.mc_asset_anim();
	this.instance_6.setTransform(-12.35,429.65,0.55,0.55,109.279,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({regX:0,regY:0,rotation:0,x:-12.3},19,cjs.Ease.cubicOut).wait(80).to({regX:-0.1,rotation:-75.4579,x:-168.6,y:429.7},19,cjs.Ease.cubicIn).to({_off:true},1).wait(141));

	// device
	this.instance_7 = new lib.mc_device();
	this.instance_7.setTransform(519.5,368.3,0.9591,0.9591,0,0,0,0.3,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({regX:0.1,x:154.6},24,cjs.Ease.cubicOut).wait(75).to({scaleX:0.6191,scaleY:0.6191,x:148.05,y:271.4,alpha:0},19,cjs.Ease.cubicInOut).to({_off:true},1).wait(141));

	// asset2
	this.instance_8 = new lib.mc_asset_anim();
	this.instance_8.setTransform(417.85,163.85,0.8104,0.8104,0,-81.726,98.274);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(14).to({_off:false},0).to({skewX:0,skewY:180,x:326.9,y:163.9},19,cjs.Ease.cubicOut).wait(66).to({skewX:65.2304,skewY:245.2304,x:506.85},19,cjs.Ease.cubicIn).to({_off:true},1).wait(141));

	// Sujet
	this.instance_9 = new lib.mc_sujet();
	this.instance_9.setTransform(150,300.15,1.3138,1.3138,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({regX:0.1,scaleX:0.85,scaleY:0.85,x:150.1,y:300.1},24,cjs.Ease.cubicOut).to({regX:0,regY:0,scaleX:0.75,scaleY:0.75,x:150,y:300},207).wait(3).to({regY:0.1,scaleX:1.3138,scaleY:1.3138,y:300.15},25,cjs.Ease.cubicInOut).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-455.5,74.4,1166.6,1187.8999999999999);
// library properties:
lib.properties = {
	id: '0318749B0FE9784AA70C70E565BB677C',
	width: 300,
	height: 600,
	fps: 25,
	color: "#CCCCCC",
	opacity: 1.00,
	manifest: [
		{src:"./Bitmap11111111111111111.png?1733751086512", id:"Bitmap11111111111111111"},
		{src:"./hpa_slots_bg.jpg?1733751086512", id:"hpa_slots_bg"},
		{src:"./hpa_slots_quali_asset1.png?1733751086512", id:"hpa_slots_quali_asset1"},
		{src:"./hpa_slots_quali_device.png?1733751086512", id:"hpa_slots_quali_device"},
		{src:"./hpa_slots_quali_device2.png?1733751086512", id:"hpa_slots_quali_device2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0318749B0FE9784AA70C70E565BB677C'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;